# Generated by Django 5.2.7 on 2025-10-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foster_home_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='foster_home_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
