# Generated by Django 5.2.7 on 2025-10-16 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_adoptionrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionrequest',
            old_name='request_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='usermanagement.pet'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Reviewing', 'Reviewing'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Adopted', 'Adopted')], default='Applied', max_length=20),
        ),
    ]
