# Generated by Django 5.2.7 on 2025-10-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_rename_request_date_adoptionrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird')], default='dog', max_length=10),
        ),
    ]
