# Generated by Django 5.2.7 on 2025-10-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_adopter_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
