# Generated by Django 5.2.7 on 2025-10-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0010_register_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Adopter',
        ),
        migrations.DeleteModel(
            name='Shelter',
        ),
    ]
