# Generated by Django 5.2.7 on 2025-10-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0012_adopter_shelter_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Adopter',
        ),
        migrations.DeleteModel(
            name='Shelter',
        ),
    ]
