# Generated by Django 5.2.7 on 2025-10-17 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0014_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adopter',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'adopter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
